import { wallpapers } from './wallpapers.js';

export const themes = {
  default: {
    id: "default",
    name: "Windows Default",
    colorSchemeId: "default",
    wallpaper: null,
    soundScheme: "Default",
    iconScheme: "default",
  },
  "60s-usa": {
    id: "60s-usa",
    name: "The 60's USA",
    colorSchemeId: "60s-usa",
    wallpaper: wallpapers.themes.find((w) => w.id === "the60sUSA").src,
    soundScheme: "60s USA",
    iconScheme: "60s-usa",
  },
  "dangerous-creatures": {
    id: "dangerous-creatures",
    name: "Dangerous Creatures",
    colorSchemeId: "dangerous-creatures",
    wallpaper: wallpapers.themes.find((w) => w.id === "dangerousCreatures").src,
    soundScheme: "Dangerous Creatures",
    iconScheme: "dangerous-creatures",
  },
  baseball: {
    id: "baseball",
    name: "Baseball",
    colorSchemeId: "baseball",
    wallpaper: wallpapers.themes.find((w) => w.id === "baseball").src,
    soundScheme: "Baseball",
    iconScheme: "baseball",
  },
  jungle: {
    id: "jungle",
    name: "Jungle",
    colorSchemeId: "jungle",
    wallpaper: wallpapers.themes.find((w) => w.id === "jungle").src,
    soundScheme: "Jungle",
    iconScheme: "jungle",
  },
  space: {
    id: "space",
    name: "Space",
    colorSchemeId: "space",
    wallpaper: wallpapers.themes.find((w) => w.id === "space").src,
    soundScheme: "Space",
    iconScheme: "space",
    screensaver: "space",
  },
  underwater: {
    id: "underwater",
    name: "Underwater",
    colorSchemeId: "underwater",
    wallpaper: wallpapers.themes.find((w) => w.id === "underwater").src,
    soundScheme: "Underwater",
    iconScheme: "underwater",
    screensaver: "underwater",
  },
  //'memphis-milano': {
  //  id: 'memphis-milano',
  //  name: 'Memphis Milano',
  //  colorSchemeId: 'memphis-milano',
  //  wallpaper: null,
  //  soundScheme: 'Default',
  //},
  "inside-your-computer": {
    id: "inside-your-computer",
    name: "Inside Your Computer",
    colorSchemeId: "inside-your-computer",
    wallpaper: wallpapers.themes.find((w) => w.id === "insideYourComputer").src,
    soundScheme: "Inside Your Computer",
    iconScheme: "inside-your-computer",
  },
  sports: {
    id: "sports",
    name: "Sports",
    colorSchemeId: "sports",
    wallpaper: wallpapers.themes.find((w) => w.id === "sports").src,
    soundScheme: "Sports",
    iconScheme: "sports",
  },
  "leonardo-da-vinci": {
    id: "leonardo-da-vinci",
    name: "Leonardo da Vinci",
    colorSchemeId: "leonardo-da-vinci",
    wallpaper: wallpapers.themes.find((w) => w.id === "leonardoDaVinci").src,
    soundScheme: "Leonardo da Vinci",
    iconScheme: "leonardo-da-vinci",
  },
  "more-windows": {
    id: "more-windows",
    name: "More Windows",
    colorSchemeId: "more-windows",
    wallpaper: wallpapers.themes.find((w) => w.id === "moreWindows").src,
    soundScheme: "Default", // Or create a new sound scheme if one exists
    iconScheme: "more-windows",
  },
  mystery: {
    id: "mystery",
    name: "Mystery",
    colorSchemeId: "mystery",
    wallpaper: wallpapers.themes.find((w) => w.id === "mystery").src,
    soundScheme: "Mystery",
    iconScheme: "mystery",
  },
  nature: {
    id: "nature",
    name: "Nature",
    colorSchemeId: "nature",
    wallpaper: wallpapers.themes.find((w) => w.id === "nature").src,
    soundScheme: "Nature",
    iconScheme: "nature",
  },
  science: {
    id: "science",
    name: "Science",
    colorSchemeId: "science",
    wallpaper: wallpapers.themes.find((w) => w.id === "science").src,
    soundScheme: "Science",
    iconScheme: "science",
  },
  "the-golden-era": {
    id: "the-golden-era",
    name: "The Golden Era",
    colorSchemeId: "the-golden-era",
    wallpaper: wallpapers.themes.find((w) => w.id === "theGoldenEra").src,
    soundScheme: "The Golden Era",
    iconScheme: "the-golden-era",
  },
  travel: {
    id: "travel",
    name: "Travel",
    colorSchemeId: "travel",
    wallpaper: wallpapers.themes.find((w) => w.id === "travel").src,
    soundScheme: "Travel",
    iconScheme: "travel",
  },
  "windows-98": {
    id: "windows-98",
    name: "Windows 98",
    colorSchemeId: "windows-98",
    wallpaper: wallpapers.themes.find((w) => w.id === "windows98").src,
    soundScheme: "Windows 98",
    iconScheme: "windows-98",
  },
};
